### ISSUE TITLE
Creating invoice fails when leaving collaborators empty

### ISSUE THREAD

**Issue by SchmittLea** [centrifuge/go-centrifuge#1038]
### Bug reports
I created an invoice and left the "write_access" blank

"write_access": {
    "collaborators": [
    	""
    	]
  }

#### Expected behaviour 
transaction going through? :) 

#### Actual behaviour
the transaction didn't go through

{
    "job_id": "0xdaf23ac6d9704b07a1e7c3fedcac7ef2",
    "status": "failed",
    "message": "[failed to anchor document: document anchoring failed: failed to send anchored document: [failed to send document to the node: bytecode for deployed identity contract 0x0000000000000000000000000000000000000000 not correct]]",
    "last_updated": "2019-05-15T09:04:30.195757Z"
}

>> if I do this, it works:
"write_access": {
    "collaborators": []
  }

**Comment by lucasvo** [comment]
This is likely going to be outdated when we rewrite the API. Leaving it open until we can confirm it's fixed.
