### ISSUE TITLE
Api definition naming/organizing should have one strategy 

### ISSUE THREAD

**Issue by rdinicut** [centrifuge/go-centrifuge#1044]
We use packages for apis:
```
package fun
package inv
package po  
```
and we have the Domain name in the types
```
InvoiceResponse
InvoiceData etc
```
We should chose one strategy not both because we get messed up api definitions
```
invInvoiceData
```
If we use packages we should have more generic names for types, Ex: Data,Response
or we should use just one package and keep Domain prefixes InvoiceResponse, InvoiceData

**Comment by lucasvo** [comment]
I am closing this as we are rewriting the APIs. @vedhavyas can you take any feedback from this into consideration for the new APIs?
