### ISSUE TITLE
Webhook call should not use document_id for job_id

### ISSUE THREAD

**Issue by rdinicut** [centrifuge/go-centrifuge#1057]
When a webhook is called for a job on document the `document_id` is actually the `job_id`.
We should add another field job_id and always have the the `document_id` set to the actual identifier of the document

At the moment you receive you mint an NFT the NotificaitonMessage is:
```
{
  event_type: 2,
  recorded: { seconds: 1558364720, nanos: 910086000 },
  document_type: 'http://github.com/centrifuge/go-centrifuge/jobs/#Job',
  status: 'pending', // This should be success
  document_id: '0xce4f423122634f478b93ef802a0eb798', // this should be the document_id 
  account_id: '0x5f2bBFcf948a0083bbE77C0aD97A64142D6b1D48' 
}
```

**Comment by mikiquantum** [comment]
As things are in the backend job implementation. The Job when it finishes doesn't know about the document/s and operations that have been performed internally. This will need a refactoring to include a list of artifacts created/updated by the underlaying tasks.
