### ISSUE TITLE
Define migration file item to convert invoice data model to new format

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#1062]
As part of the work to break up our Protocol API, we are changing the data format of every document type.
Create migration file that performs:
From:
```json
{
   ...
   cd_root: "",
   number: "",
   currency: "",
   ...
}
```
To:
```json
{
   ...
   cd_root: "",
   data: {
      number: "",
      currency: "",
      ...
   }
}
```
Other models to follow soon.

**Comment by pstehlik** [comment]
is this still relevant or can we close this and the respective epic?

**Comment by mikiquantum** [comment]
We can close this and the epic.
