### ISSUE TITLE
createconfig should not require http or https prefix

### ISSUE THREAD

**Issue by manuelpolzhofer** [centrifuge/go-centrifuge#1204]
###  Good First Issue
A good first issue for new developers.  Contributions are always very welcome.

##  Problem
The `centrifuge createconfig` command requires for the  parameter `-e, --ethnodeurl string`  a URL with an `http` or `https` prefix.

More information: https://developer.centrifuge.io/docs/getting-started/install-cent-node/

### Current behaviour
Example: `-e rinkeby.infura.io/v3/<CUSTOM PART>` fails
Example: `-e https://rinkeby.infura.io/v3/<CUSTOM PART>`works
##

### Correct behaviour
Example: `-e rinkeby.infura.io/v3/<CUSTOM PART>`  works
Example: `-e https://rinkeby.infura.io/v3/<CUSTOM PART>` works

### Solution
Check if passed url contains `http` or `https` prefix if not add by default `https`

###  Why?
Currently, Infura provides a default project link without an `http` or `https` prefix.

Copy/paste from Infura would result in an error which is bad onboarding experience for new users.

**Comment by lucasvo** [comment]
We should also verify it is a correct url, if a prefix is defined, i.e. you can't specify `ftp://....`
