### ISSUE TITLE
Update Go Node APIs + New Identity Types

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#1521]
Following on this spec: https://centrifuge.hackmd.io/vYHYKA4ATIaP-85dANZ9yw?both#Operation-Flows-from-GO-Node-Perspective

[Fill this issue with the above plan]

**Comment by cdamian** [comment]
Done in - https://github.com/centrifuge/go-centrifuge/pull/1545

**Comment by mustermeiszer** [comment]
Can I close this @cdamian ?

**Comment by cdamian** [comment]
@mustermeiszer Sure, I'll close it.
