### ISSUE TITLE
Add pre-commit

### ISSUE THREAD

**Issue by vedhavyas** [centrifuge/go-centrifuge#184]
Tasks:
* Change the client api to allow skipping the pre commit step
* Check when modifying a document if a pre commit exists and return an error to the user if another party has a lock
* Implement Pre Commit P2P Server & Client methods
* Implement smart contract on node to submit pre commit message
* Functional test for pre commit

Specific places to look out for:
github.com/centrifuge/go-centrifuge/centrifuge/anchors/ethereum_anchor_repository.go
`func (ethRepository *EthereumAnchorRepository) PreCommitAnchor(anchorID AnchorID, signingRoot DocRoot, centrifugeId identity.CentID, signature []byte, expirationBlock *big.Int) (confirmations <-chan *WatchPreCommit, err error)`

```
	//confirmations, err = setUpPreCommitEventListener(ethRepositoryContract, opts.From, preCommitData)
	//if err != nil {
	//	wError := errors.Wrap(err, 1)
	//	log.Errorf("Failed to set up event listener for pre-commit transaction [id: %x, signingRoot: %x, SchemaVersion:%v]: %v",
	//		preCommitData.AnchorID, preCommitData.SigningRoot, preCommitData.SchemaVersion, wError)
	//	return
	//}
```

2. 
github.com/centrifuge/go-centrifuge/centrifuge/coredocument/processor/processor.go

```
// TODO documentProofs has to be included when we develop precommit flow
	confirmations, err := dp.AnchorRepository.CommitAnchor(anchorID, rootHash, centID, [][anchors.DocumentProofLength]byte{tools.RandomByte32()}, mac)
	if err != nil {
		return fmt.Errorf("failed to commit anchor: %v", err)
	}
```

```
// TODO documentProofs has to be included when we develop precommit flow
	confirmations, err := anchors.CommitAnchor(anchorID, rootHash, myCentID, [][anchors.DocumentProofLength]byte{tools.RandomByte32()}, mac)
	if err != nil {
		log.Error(err)
		return centerrors.Wrap(err, "anchoring error")
	}
```

Note: 
File `anchors/ethereum_anchor_repository.go` function `generateEventContext` should read context same way as commit flow.

**Comment by lucasvo** [comment]
Closing this. Duplicate
