### ISSUE TITLE
Use prefixed field in merkle tree for data tree

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/go-centrifuge#245]
The data tree right now does not prefix fields with anything so we could theoretically have conflict between two identically named fields in CoreDocument and InvoiceData. We should modify precise-proofs to allow setting a prefix for all leaves when flattening the message.

We should export `messageFlattener` in precise-proofs and allow more customization of its behavior. One such customization should be the label prefix (this already is a function argument for the flattener). 

```json,
CoreDocument = {
    "name": "Foo",
    "embedded_data": { "name": "Bar"}
}
```

Would lead to a tree that has two leaves that conflict: `"name,Bar,salt", "name,Foo,salt"` if we construct the `DataTree` without setting a prefix. 

The prefix should be ["invoice", "po"]

This will change the format of the fields to be proven as well in the NFT (makes sense to implement with https://github.com/centrifuge/centrifuge-ethereum-contracts/issues/52)

**Comment by rdinicut** [comment]
If we use document_type.field_name we will have a gas reduction in the mint method as we do not need to send the document type proof anymore, which is a plus. 
The downside will be that we will leak the document type by default and it is a privacy issue. You do not have full control of the data you share when generating a proof

**Comment by mikiquantum** [comment]
Will take care here of https://github.com/centrifuge/roadmap/issues/55, of node and precise-proof related ones. precise-proof js will be taken care separately.
