### ISSUE TITLE
[Webhook] Add from/to Peer to the Protobuf message and adapt code

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#489]
Protobuf Message:
```
message NotificationMessage {
  uint32 event_type = 1;
  string from = 6;
  string to = 8;
  google.protobuf.Timestamp recorded = 3;
  string document_type = 4;
  string document_id = 7;
}
```
Fill new fields accordingly in the code.

**Comment by lucasvo** [comment]
I don't think the 'from/to' is the right naming. It's not entirely clear which field defines the tenant. I would just add one field called `identity`. Given not all notifications will have a destination identity I would remove that from the standard notifications.

**Comment by vedhavyas** [comment]
Why not we rename then as sender(who triggered the notification) and receiver instead ?

**Comment by mikiquantum** [comment]
Final agreement:
```
{
  account_id string,
  from_id string,
  to_id string
}
```
