### ISSUE TITLE
Uniqueness of documents for NFT

### ISSUE THREAD

**Issue by manuelpolzhofer** [centrifuge/go-centrifuge#519]
Requirement: P2P Layer supports the [uniqueness fields as laid out in the P2P Epic](https://hackmd.io/Wy78jBRfQWSz6KLU21pk4A?both#NFT-Support).

It is only allowed once to mint an NFT for a document.

Therefore  information about the NFT will be added inside the document.

According to [privacy-enabled NFT paper](https://github.com/centrifuge/paper-privacy-enabled-nfts/blob/master/main.tex#L189).
```json
"documentIdentifier": "0x...",
    // [...]
 	"onChainRegistrations": [
		// Registration:
		{
			"type": "0x...", // uint256
			"registry": "0x...", // address (20byte)
			"tokenID": "0x..." // uint256
			"concatRegistration": "..." // string
		},
	]
	// [...]
```

## Workflow
1. User A wants to mint an NFT.
2. User A creates a new random NFT tokenID.
3. User A adds the type,registry and tokenID to the document.
4. Request Signature from all other collaborators
5. Commit updated document to anchorRepository contract.
6. Call NFT mint method with additional proof for tokenId
 
```javascript

require(
MerkleProofSha256.verifyProof(
_proofs[tokenIdIdx],
_merkleRoot,
//same tokenId can't be minted twice
_hashLeafData(supportedFields_[tokenIdIdx], tokenId, _salts[tokenIdIdx])
),
      "merkle tree needs to validate the tokenId"
    );
    
    
```

**Comment by vimukthi-git** [comment]
@vedhavyas could you comment on whats complete here? may be we can close this?
