### ISSUE TITLE
Remove GRPC from API

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#615]
As we are not using GRPC on the p2p layer, we shouldn't use it on the API side. 
We should remove GRPC gateway logic and plugin usage with protobufs.

#### Testing
<Describe required tests: Unit, Integration, Testworld or Functional>

#### Acceptance Criteria
<What is the acceptance criteria of this ticket?>

#### Dependencies and affected external components
<Outline any dependencies and components that could be affected by this>

**Comment by lucasvo** [comment]
I'll close this as this is clearly an epic level thing we need to discuss in a different format than on a go-centrifuge issue :)
