### ISSUE TITLE
Error on first lauch: key_registration_confirmation_task.go:169

### ISSUE THREAD

**Issue by Remi-Tuy** [centrifuge/go-centrifuge#638]
### Bug reports

after make install on first lauch the node errors with the following start command: 

`go-centrifuge createconfig -z  ~/.ethereum/keystore/xxxxxxxxxxxxxxxxxx -k "xxxxxxxxxx" -e "https://kovan.infura.io/v3/xxxxxxxxxxxxxxxxxxxxx" -t . -a 8082 -p 38204 -n "bernalheights" -x=false`

#### Expected behaviour 

node should connect to peers and send keys to the network:

#### Actual behaviour

`14.01.2019 12:19:33.023   WARNING   geth-client:  Ethereum Client doesn't support txpool API, may cause transactions failures geth_client.go:273
14.01.2019 12:19:33.024   INFO   identity:  Waiting for confirmation for the Key [7086fa4cafedfd507a0e57b6a77c4f8533f6d705000000000000000000000000] key_registration_confirmation_task.go:144
14.01.2019 12:19:33.215   INFO   identity:  Sent off key [3:7086fa4cafedfd507a0e57b6a77c4f8533f6d705000000000000000000000000] to add to CentrifugeID [CentrifugeID [0x7bed13811b08]]. Ethereum transaction hash [5fd46d768dd025107cf9a25772c243d445dde4d68d6a813fe140609655257ba0] ethereum_identity.go:281
14.01.2019 12:19:44.369   INFO   identity:  Received filtered event Key Registration Confirmation for CentrifugeID [0x7bed13811b08] and key [7086fa4cafedfd507a0e57b6a77c4f8533f6d705000000000000000000000000] with purpose [3]
 key_registration_confirmation_task.go:169`

#### Steps to reproduce the behaviour

1. pull develp branch on new machine
2. make install
3. run: `go-centrifuge createconfig -z  ~/.ethereum/keystore/xxxxxxxxxxxxxxxxxx -k "xxxxxxxxxx" -e "https://kovan.infura.io/v3/xxxxxxxxxxxxxxxxxxxxx" -t . -a 8082 -p 38204 -n "bernalheights" -x=false`

**Comment by Remi-Tuy** [comment]
Mb this just creates the config and does not run the node.

Maybe would be good to have a success message at the end of the config.yml creation, would avoid confusions.

**Comment by vimukthi-git** [comment]
Closing this as this is the expected behaviour, you need to run
`centrifuge run -c <config file generated above>`

**Comment by vimukthi-git** [comment]
I will hand this over to someone to add a message here.

**Comment by charleenfei** [comment]
Thanks for the suggestion @Remi-Tuy , I've added the success message.
