### ISSUE TITLE
[MultiAccounts][bug] The secondary accounts do not work after node restart

### ISSUE THREAD

**Issue by vimukthi-git** [centrifuge/go-centrifuge#691]
The secondary accounts do not work after node restart, 

#### Expected behaviour 
- Secondary accounts must always work regardless of node restart

#### Actual behaviour
- The secondary accounts do not work after node restart, 

#### Steps to reproduce the behaviour
- Run test world `addExternalCollaborator_withinHost` test twice.

**Comment by mikiquantum** [comment]
FIxed by https://github.com/centrifuge/go-centrifuge/pull/701
