### ISSUE TITLE
Convert transaction IDs returned from API into hex and accept hex encoded txIDs when received

### ISSUE THREAD

**Issue by vimukthi-git** [centrifuge/go-centrifuge#692]
Suggested Impl:

We can define a type like the following

```
type TxID *uuid.UUID

func (tid TxID) String() {
   // convert tid to hex string
}

func FromString(tidHex string) TxID {
// convert tid hex string to TxID
}

```

Then use the above type everywhere we use the current UUID based tx ID.

#### Testing
- Tests for above type
- Testworld should pass

#### Acceptance Criteria
- All Client APIs return hex converted TX IDs
- All Client APIs accept hex encoded TX IDs if they require.

cc @lucasvo @vedhavyas

**Comment by lucasvo** [comment]
Does it make sense to actually derive it from UUID? Why not derive it from the type ethereum uses internally for IDs?

**Comment by lucasvo** [comment]
Also I'd like to use completely random UUIDs and nothing that has a timestamp by default.

**Comment by vedhavyas** [comment]
We are using uuid v4 which is completely random. Timestamp will not be part of it

But I don't understand the previous comment about deriving
