### ISSUE TITLE
Remove acl logic into model

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#707]
Spec changes @charleenfei 

Follow work done by https://github.com/centrifuge/go-centrifuge/issues/716

#### Testing
<Describe required tests: Unit, Integration, Testworld or Functional>

#### Acceptance Criteria
<What is the acceptance criteria of this ticket?>

#### Dependencies and affected external components
<Outline any dependencies and components that could be affected by this>

**Comment by charleenfei** [comment]
closing this issue due to redundancy with #716
