### ISSUE TITLE
Write converter between client protobuf and model

### ISSUE THREAD

**Issue by pstehlik** [centrifuge/go-centrifuge#714]
Implement the client-facing APIs to accommodate the changes of #713.

# Testing
* All combinations of custom field types (binary, int, dec, string, bool)

# Acceptance Criteria
* Testworld test-cases and all the other usual stuff
* Documentation is updated
* Announce the API changes in release notes and to users.

# Dependencies and affected external components
Keep the documentation in mind -> update the docs with new example calls.
Announce the API changes in release notes and to users.

**Comment by lucasvo** [comment]
This could make custom fields a bit simpler to handle: https://github.com/centrifuge/precise-proofs/issues/38 I've asked @vimukthi-git to review and make sure we can merge it.
