### ISSUE TITLE
Signatures refactor

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#732]
1) Important: signature_id is identity (20 bytes) + pub key (32 bytes)
2) SignatureData should be used to create the SignaturesRoot
3) CoreDocumentRoot is a tree with two manually appended hashes (signing root and signatures root)
4) When append_field option is implemented, use it for signatures (https://github.com/centrifuge/precise-proofs/issues/55)

```
protobuf,
message SignatureData {
   repeated Signature signatures = 1 [
    (proofs.key_length) = 52,
    (proofs.mapping_key) = "signature_id"
  ];
}

message Signature {
  bytes signature_id = 1; // This should be entity_id+public_key
  // `entity_id` is the CentrifugeID of the entity signing the document.
  bytes entity_id = 1;
  // `public_key` is the public key of the `entity` used for signing the `CoreDocument`
  bytes public_key = 2;
  bytes signature = 3;
  google.protobuf.Timestamp timestamp = 4;
}

message CoreDocument {
    SignatureData signature_data = 1 [
    (proofs.exclude_from_tree) = true
  ];

}
```

#### Testing
<Describe required tests: Unit, Integration, Testworld or Functional>

#### Acceptance Criteria
<What is the acceptance criteria of this ticket?>

**Comment by vimukthi-git** [comment]
@lucasvo Is this not what you suggested in my PR? please make those suggestions here, if they are different.

**Comment by mikiquantum** [comment]
Fixed by: https://github.com/centrifuge/go-centrifuge/pull/791
