### ISSUE TITLE
Add prefix to subtrees

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#755]
We need to add a deterministic prefix to the coredocument tree and signing tree.
Both for human readable and compact property.

Open questions:
- Should we adapt the proof value to take the prefix? or abstract that logic to the node, to always try all the trees for a property match. What if compact property has a match in 2 trees (bad)?

Keep in sync with NFT hardcoded proofs.

#### Testing
<Describe required tests: Unit, Integration, Testworld or Functional>

#### Acceptance Criteria
<What is the acceptance criteria of this ticket?>

#### Dependencies and affected external components
<Outline any dependencies and components that could be affected by this>

**Comment by lucasvo** [comment]
For now, let's not abstract it away from the client, it's a source of errors (and security issues).

**Comment by mikiquantum** [comment]
I am leaning towards that as well. Let's make sure then we give Razvan the new compact properties so they can be hardcoded in the NFT SCs.

**Comment by vedhavyas** [comment]
@vimukthi-git can we close this?

**Comment by vimukthi-git** [comment]
@vedhavyas nope, the signing tree prefixes needs to be handled with this

**Comment by mikiquantum** [comment]
Closing this as the signature tree will add the prefix as part of its own spec.
