### ISSUE TITLE
Hide next version on NFT mint method 

### ISSUE THREAD

**Issue by vimukthi-git** [centrifuge/go-centrifuge#778]
We need to hide the next version of a document when minting an NFT of it. The solution is,
- Introduce a next_secret field to the coredoc
- Every time a document is updated(anchored),
    - The `next_preimage` field of the previous version of the document is to be used as the anchor ID
    - Set `next_version = sha256(next_preimage)`
    - Set `next_preimage= random 32bytes`
- Update AnchorRepository contract to take the `next_preimage` as the anchor ID param(say `anchorValue`) and save `commits[sha256(anchorValue)] = docRoot`
- Submit next_version proof in the nft minting logic in the node (if its not already there)

cc @lucasvo @manuelpolzhofer @rdinicut  

#### Testing
- All existing tests pass
- New tests for verifying next version logic

#### Acceptance Criteria
- next_version is not exposed in the mint method calls
- precommit, commit and nft minting works

**Comment by lucasvo** [comment]
Let's call it 'next_preimage' and use sha256 instead of keccak, as we're using sha256 everywhere else

**Comment by vimukthi-git** [comment]
@lucasvo sure.

**Comment by manuelpolzhofer** [comment]
the `next_version` would be still exposed but the `next_preimage` is actually required to add the `next_version` anchor.
