### ISSUE TITLE
Defining the meaning of a signature on a state (version)

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/go-centrifuge#795]
When a node signs a document the meaning of that signature is not entirely clear. There are multiple scenarios where it can mean one of the two things and we currently do not have a way to differentiate the two.

1) I signed off on the transition from `d -> d'`
2) I have received `d'`

There are different scenarios where this can happen:

1) Node added as a new collaborator: if this is simply the first version a node should be able to read, the case *1* would be impossible so the meaning must be *2*. 
2) The node doesn't have the previous version and can therefore only attest to the receipt (e.g. if the data is missing). We can work around this by also sending the previous version and the node can verify that the transition is indeed correct.

However there is a third scenario that is not as simple to deal with:

Let's assume you have `d_1 -> d_2 -> d_3 -> d_4`. A collaborator signed `d_1` but then went offline. In the meantime two new versions (`d_2, d_3`) are published. After that the collaborator comes back online. And another node wants to publish `d_3 -> d_4` What should happen now? Technically it's not enough to verify `d_3 -> d_4` and sign saying the transition is valid. The node should also check `d_2 -> d_3`. If the node wasn't able to check `d_2 -> d_3` because it wasn't given `d_2`, what should it do? If it does, how does it specify what the signature means?

Possible solution: Extend the signature to sign the current signing root along with the last good version. If the node is able to verify it all the way back to `d_1`, that's ideal and if not, it could specify what it has seen.

Acceptance criteria:
- Make sure collaborators can be accessed at a later point in time
- Testworld coverage for different signature meanings

**Comment by vimukthi-git** [comment]
sending the previous version may not be an option since it opens up possibility of document being exposed to unauthorised access i.e for a new collaborator. Best way is for the receiving node to request for the document if it doesn't have it. Then the node that receives the request for previous version can verify whether the requester has correct access permissions.

**Comment by vedhavyas** [comment]
I actually like the solution where node explicitly request for previous document and verifies it and then signs the update. This brings me to next question. What if for some reason, the collaborator do not have read access to the documents he/she missed? So when collaborator asks for the those documents, the request will be denied. In this case should the collaborator still sign the latest version ?

**Comment by lucasvo** [comment]
@vedhavyas that's why the signature needs to have a "meaning", i.e. I sign the transition or just the receipt of state X. If you don't have access to the previous version, then you wouldn't sign with the other purpose

**Comment by vimukthi-git** [comment]
Discussion
- Lets have a nonce(4 bytes) for each update to the document so that a node receiving a document can specify which nonce(version) n onwards the it is validating the transitions for. This also has the benefit of the node being able to know how many versions of the document are missing in its db.
- The signature should be made on (signature root + nonce) while the signature protobuf also including the set of values concatenated to create the signature.

cc @lucasvo

**Comment by vimukthi-git** [comment]
More comprehensive document https://hackmd.io/BXsOO8GTQpGomkweh-8Yvg?both
cc @vedhavyas @mikiquantum @lucasvo

**Comment by vedhavyas** [comment]
Post dicussion between @lucasvo and I, we will reduce the scope of this ticket to adding a boolean value to the signature payload. if the collaborator can access the previous document, its true else false.

Acceptence criteria:
- Add boolean and verify the signature
- Add test world case that adds a new collaborator for an update who returns false and next update should return true

**Comment by mikiquantum** [comment]
Will move to feature branch

**Comment by mikiquantum** [comment]
Fixed by https://github.com/centrifuge/go-centrifuge/pull/1107
