### ISSUE TITLE
Timestamps and authors in CoreDocument

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/go-centrifuge#809]
We need to add the timestamp a change was made to the CoreDocument as well as who made the change so that when signing a state update that is clearly tied to a particular time and coming from a particular node.

In addition to adding two fields, we should add some extra validations:
1) Sender of the request needs to be the author of the document
2) When receiving a signature request, one should only sign a document that has a timestamp < 10min in the past

**Comment by vimukthi-git** [comment]
@lucasvo I just realise that we record timestamp in the coredocumentpb.Signature data structure. Since we also have the sender field to record who made the change, we already have this record. Just need to add the 2nd validation you mention. 
Therefore the issue could be simplified to just,
1. Add the sender.
2. Validation the senders signature and key in the signature list.
3. Validate timestamp.

Does this make sense?

**Comment by lucasvo** [comment]
The signature timestamp is not part of the signature payload, right? So that alone won't be enough. I think we should add a change date to the document and add a set of validations:

General validation:
1) Ensure that the document change date - anchor timestamp < MAX_DOC_CHANGE_ANCHOR_DELTA
2) Ensure that the signature date is > doc change date 
3) Ensure that signature date is < anchor timestamp

When requesting a pre commit (so in the sign method):
* Ensure that document change date - now < MAX_DOC_CHANGE_ANCHOR_DELTA
* 2 & 3 Apply as well.

**Comment by lucasvo** [comment]
As discussed earlier, we should remove the date on the signature. We will instead always assume that signature date == document timestamp. I would name the constant `MaximumDocumentTimestampAnchorTimeDifference` and let's set it to 3600 seconds (1hr).

**Comment by vimukthi-git** [comment]
@lucasvo the implementation now is the following (as requested)
### PostAnchor
- Validate all signatures are validated against doc timestamp (no sig timestamp anymore)
- Validate author has signed 
- Validate Signers are signer collaborators
- Validate document was anchored within `MaxAuthoredToCommitDuration` which is 2 hours.

### PreAnchor
- Collaborators only sign a document within `MaxAuthoredToCommitDuration` which is 2 hours.
- Signature req Sender is author
