### ISSUE TITLE
Error messages can be used to leak the collaborators list

### ISSUE THREAD

**Issue by vedhavyas** [centrifuge/go-centrifuge#914]
We need to make sure all forms of non-access to a document return the same error message: invalid token, invalid user, nonexistent document etc.

This might also be affected:
https://github.com/centrifuge/go-centrifuge/commit/1e6e30cebae074f070f231d58f2a4dc5e7869ae4

**Comment by pstehlik** [comment]
hey folks, which PR was used for this fix?

**Comment by mikiquantum** [comment]
https://github.com/centrifuge/go-centrifuge/pull/944
