### ISSUE TITLE
NFT Token ID not compatible with Dharma loan issuance

### ISSUE THREAD

**Issue by Remi-Tuy** [centrifuge/go-centrifuge#921]
### Bug reports
The id of the NFT minted based on a document is too long to be accepted by Dhrama Protocol
In this file on line 119: https://github.com/dharmaprotocol/dharma.js/blob/774eee1693e1375d30df7ab0a63418dd4d5d5cfc/src/adapters/erc721_collateralized_simple_interest/loan_terms.ts

it says the following: // Token reference has a maximum value that cannot be exceeded due to how we pack params.

After testing that max value is 15 characters long but the cent_token_id is way over that
#### Expected behaviour 
Token ID to be accepted by both Dharma.js and the Dharma TermsContract smart contract

#### Actual behaviour
Token ID gets rejected when trying to issue a loan using dharma.js
Not tested at protocol level yet but in progress.

**Comment by Remi-Tuy** [comment]
According to a private conversation with @pstehlik the token id is generated randomly on the CENT node.
Maybe it could be limited to a certain number of characters ?

**Comment by Remi-Tuy** [comment]
Looking deeper in the Dharma contract ERC721Enumerable.sol references to the token by id (see https://github.com/dharmaprotocol/charta/blob/master/contracts/ERC721Collateralizer.sol on line 378, 255, 290, 283) The only way we see to make it work is to modify the collateralizer and add the Enumarable function tokenByIndex().

**Comment by Remi-Tuy** [comment]
After even more research we are not sure how to get the index of the token with the token id.
The only identifier we get from the CENT node is the token id, and with standard ERC721 there are not method to get the token index based on the token id.

**Comment by pstehlik** [comment]
link to https://github.com/centrifuge/centrifuge-ethereum-contracts/issues/137

**Comment by pstehlik** [comment]
Will be fixed by #951
