### ISSUE TITLE
Document what happens if CentNode gets killed/shutdown

### ISSUE THREAD

**Issue by pstehlik** [centrifuge/go-centrifuge#925]
Document these things:
* what happens to ETH transactions that are pending?
* what happens to transactions that are running in go-celery
* what state will the node be in when it comes back up/is restartet
... ?

**Comment by vimukthi-git** [comment]
created https://hackmd.io/4CLMcShCR6aib1eYZ4q0cA

cc @pstehlik @lucasvo @vedhavyas @mikiquantum
