### ISSUE TITLE
Change logging/naming of "transactions" (internal node TXs vs Ethereum TXs)

### ISSUE THREAD

**Issue by pstehlik** [centrifuge/go-centrifuge#926]
It is really tough to know which "transaction" is being talked about in logs and API returns.

* Change the logging to be clear when the log entry talks about an "ethereum transaction" (instead of a node internal TX).
* Change the name of the "nternal TX ("transaction") to "taskId" (or something else clear)-> making sure to distinguish the async tasks compared to transactions sent to a blockchain/Ethereum

**Comment by vimukthi-git** [comment]
As explained during last planning `task` already has a different meaning on go-centrifuge. Therefore I have a suggestion we can change the current hex encoding of the internal transaction string to make it clear that its not an ethereum transaction.
eg : replace the add a prefix like `CT` to the hex like `CT0xDE2132133214123431DADAUYGUG`. This is very easy to do, just need to change the default serialiser of `TxID` type.
cc @pstehlik @lucasvo
