### ISSUE TITLE
Add minimum response time to every p2p call

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/go-centrifuge#978]
We want to avoid having a timing attack where an invoker can figure out certain information based on the time a request takes to perform.
We should apply this to:
- Every p2p endpoint
- wether the data is available or not

Take some time to research on current average response times for above scenario to find the correct response delay.
Add this timing delay handling in the interceptor, so it is applied to all requests.

**Comment by pstehlik** [comment]
Fixed with #1013
